[env:stick-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
  m5stack/M5Unified@^0.2.12
  m5stack/M5GFX@^0.2.18
monitor_speed = 115200
upload_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 8MB
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DBOARD_HAS_PSRAM
